name: CI/CD

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          check-latest: true

      - name: Run tests
        run: go test -v ./...

  build-and-release:
    name: Build and Release
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          check-latest: true

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o am ./cmd/am
          GOOS=linux GOARCH=amd64 go build -o ggl ./cmd/ggl
          GOOS=linux GOARCH=amd64 go build -o daily ./cmd/daily
          GOOS=linux GOARCH=amd64 go build -o ical ./cmd/ical
          GOOS=linux GOARCH=amd64 go build -o obs-fm ./cmd/obs-fm
          tar -czf obsidian-utils-linux-amd64.tar.gz am ggl daily ical obs-fm

      - name: Build for Linux (arm64)
        run: |
          GOOS=linux GOARCH=arm64 go build -o am ./cmd/am
          GOOS=linux GOARCH=arm64 go build -o ggl ./cmd/ggl
          GOOS=linux GOARCH=arm64 go build -o daily ./cmd/daily
          GOOS=linux GOARCH=arm64 go build -o ical ./cmd/ical
          GOOS=linux GOARCH=arm64 go build -o obs-fm ./cmd/obs-fm
          tar -czf obsidian-utils-linux-arm64.tar.gz am ggl daily ical obs-fm

      - name: Build for macOS (amd64)
        run: |
          GOOS=darwin GOARCH=amd64 go build -o am ./cmd/am
          GOOS=darwin GOARCH=amd64 go build -o ggl ./cmd/ggl
          GOOS=darwin GOARCH=amd64 go build -o daily ./cmd/daily
          GOOS=darwin GOARCH=amd64 go build -o ical ./cmd/ical
          GOOS=darwin GOARCH=amd64 go build -o obs-fm ./cmd/obs-fm
          tar -czf obsidian-utils-darwin-amd64.tar.gz am ggl daily ical obs-fm

      - name: Build for macOS (arm64)
        run: |
          GOOS=darwin GOARCH=arm64 go build -o am ./cmd/am
          GOOS=darwin GOARCH=arm64 go build -o ggl ./cmd/ggl
          GOOS=darwin GOARCH=arm64 go build -o daily ./cmd/daily
          GOOS=darwin GOARCH=arm64 go build -o ical ./cmd/ical
          GOOS=darwin GOARCH=arm64 go build -o obs-fm ./cmd/obs-fm
          tar -czf obsidian-utils-darwin-arm64.tar.gz am ggl daily ical obs-fm

      - name: Build for Windows (amd64)
        run: |
          GOOS=windows GOARCH=amd64 go build -o am ./cmd/am
          GOOS=windows GOARCH=amd64 go build -o ggl ./cmd/ggl
          GOOS=windows GOARCH=amd64 go build -o daily ./cmd/daily
          GOOS=windows GOARCH=amd64 go build -o ical ./cmd/ical
          GOOS=windows GOARCH=amd64 go build -o obs-fm ./cmd/obs-fm
          tar -czf obsidian-utils-windows-amd64.tar.gz am ggl daily ical obs-fm

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            bsidian-utils-linux-amd64.tar.gz
            bsidian-utils-linux-arm64.tar.gz
            bsidian-utils-darwin-amd64.tar.gz
            bsidian-utils-darwin-arm64.tar.gz
            bsidian-utils-windows-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}