name: Pull Request Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.23.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v ./...

    - name: Build all utilities
      run: |
        go build -v ./cmd/am
        go build -v ./cmd/daily
        go build -v ./cmd/ggl
        go build -v ./cmd/ical
        go build -v ./cmd/obs-fm